apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx
  namespace: default
spec:
  replicas: 2
  strategy:
    canary:
      steps:
      - setWeight: 10
        pause:
          duration: 10m # Pause for 10 minutes at 10%
      - setWeight: 50
        pause:
          duration: 5m  # Pause for 5 minutes at 50%
      - setWeight: 100  # Rollout to 100%
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: ptader/nginx:v2 # Update to v2
        ports:
        - containerPort: 80
