apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-canary
  namespace: default
spec:
  replicas: 2
  strategy:
    canary:
      steps:
      - setWeight: 10
      - pause: {duration: 2m}
#      - setWeight: 50
#      - pause: {duration: 1m}
      - setWeight: 100  # Rollout to 100%
  selector:
    matchLabels:
      app: nginx-canary
  template:
    metadata:
      labels:
        app: nginx-canary
    spec:
      containers:
      - name: nginx-canary
        image: ptader/nginx:v1 # Update to v2
        ports:
        - containerPort: 80
